# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PR Build Validation

on:
  workflow_dispatch: 
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/DebaitMyFeed/
    - name: Build
      run: dotnet build --no-restore src/DebaitMyFeed/
    - name: Ensure browsers are installed
      run: pwsh src/DebaitMyFeed/DebaitMyFeed.Tests/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Test
      env:
        ApiKeys__OpenAiApiKey: ${{ secrets.APIKEYS__OPENAIAPIKEY }}
        ApiKeys__MistralAiApiKey: ${{ secrets.APIKEYS__MISTRALAIAPIKEY }}
      run: dotnet test --no-build --verbosity normal src/DebaitMyFeed/